### ISSUE TITLE
Pretrained weights for DeformingThings4D and Robot

### ISSUE THREAD

**Issue by shubhMaheshwari** [jinseokbae/neural_marionette#2]
Thank you, for releasing the code for your amazing paper. 
I have to perform experiments on non-human sequences like animals and robot. Can you kindly share the trained weights for them as well.

**Comment by jinseokbae** [comment]
Hello,
We would like to send you our pre-trained models for the two dataset via e-mail.

Hope it will help your research.

Best,
Jinseok
